steps:
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['install']
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['test']
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['build']
- name: node:16
  entrypoint: echo
  args: ['test1234']