artifacts:
  objects:
    location: 'gs://homepage-338312_app/'
    paths: 'website/build/*'
steps:
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['install']
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['test']
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['build']
