runtime: nodejs20
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always
instance_class: F1
automatic_scaling:
  max_instances: 1