steps:
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['install']
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['test']
- name: node:16
  dir: 'website'
  entrypoint: yarn
  args: ['build']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  dir: 'website'
  entrypoint: 'gcloud'
  args: ['app', 'deploy', '--stop-previous-version']